[package]
name = "omniterm-desktop"
version = "0.1.0"
description = "OmniTerm desktop application"
authors = ["Ben Bencsik"]
edition = "2021"

[lib]
name = "omniterm_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
